# docker-compose.yml

version: '3.8'

services:
  web:
    build: ./django
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./django/vermillion:/vermillion
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    expose:
      - 8000
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://vermillion:vermillion@db:5432/vermillion
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`vermillion.localhost`)"
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=vermillion
      - POSTGRES_PASSWORD=vermillion
      - POSTGRES_DB=vermillion
  traefik:
    image: traefik:v2.2
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data:
