# Generated by Django 3.2.4 on 2021-06-09 03:13

import default.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image_url', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='ExposedPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', default.models.PortField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposed_ports', related_query_name='exposed_ports', to='default.containertemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Running'), (1, 'Stopped'), (2, 'Deconstructed')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='VolumeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_dir', models.CharField(max_length=4096)),
                ('required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_definitions', related_query_name='volume_definitions', to='default.containertemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_dir', models.CharField(max_length=4096)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volumes', related_query_name='volumes', to='default.volumedefinition')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', related_query_name='volumes', to='default.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePortMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traefik_port', default.models.PortField(unique=True)),
                ('container_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_mappings', related_query_name='service_mappings', to='default.exposedport')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_mappings', related_query_name='port_mappings', to='default.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('templates', models.ManyToManyField(related_name='service_definitions', related_query_name='service_definitions', to='default.ContainerTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', related_query_name='services', to='default.servicedefinition'),
        ),
        migrations.AddConstraint(
            model_name='volumedefinition',
            constraint=models.UniqueConstraint(fields=('container_dir', 'template'), name='unique_container_dir_per_template'),
        ),
        migrations.AddConstraint(
            model_name='volume',
            constraint=models.UniqueConstraint(fields=('host_dir', 'service'), name='unique_host_dir_per_service'),
        ),
        migrations.AddConstraint(
            model_name='volume',
            constraint=models.UniqueConstraint(fields=('definition', 'service'), name='unique_volume_definition_per_service'),
        ),
        migrations.AddConstraint(
            model_name='volume',
            constraint=models.UniqueConstraint(condition=models.Q(('host_dir__startswith', '/')), fields=('host_dir',), name='unique_absolute_host_dir'),
        ),
        migrations.AddConstraint(
            model_name='serviceportmapping',
            constraint=models.UniqueConstraint(fields=('service', 'container_port'), name='unique_container_port_per_service'),
        ),
        migrations.AddConstraint(
            model_name='exposedport',
            constraint=models.UniqueConstraint(fields=('template', 'port'), name='unique_exposed_port_per_container_template'),
        ),
    ]
